In [1]:
#NUMPY BASICS

In [2]:
import numpy as np

In [5]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) #1x15 vektor

In [6]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
print(array.shape)

(15,)


In [8]:
a=array.reshape(3,5)

In [9]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
print("shape",a.shape)    #aXb
print("dimension ",a.ndim) #2 boyutlu
print("data type ",a.dtype.name) #arrayıb icindeki data type isimleri 
print("size ",a.size) 
print("type ",type(a))

shape (3, 5)
dimension  2
data type  int64
size  15


In [16]:
array1=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 5]]


In [17]:
np.zeros((3,4)) #0'lardan oluşan 3x4lük matris verir 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#liste.append(5) yapmak belleği yorduğu için istediğimiz kadar alanı zeros kullanarak 0'larla doldurup
#sonradan duzenleyebiliriz.

zeros=np.zeros((3,4))
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
np.ones((3,4)) #1'lerden oluşan matris verir.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.empty((2,3)) #python bos yerine cok cok cok kucuk bir sayi atıyor

array([[2.00000000e+000, 2.68678721e+154, 1.48219694e-323],
       [0.00000000e+000, 0.00000000e+000, 4.17201348e-309]])

In [23]:
a=np.arange(10,50,5) #10'dan 50'ye kadar (50 dahil degil) 5'er arttırarak yazar.
a

array([10, 15, 20, 25, 30, 35, 40, 45])

In [26]:
a=np.arange(1,35,3.5) 
a

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5])

In [27]:
a=np.linspace(10,50,20) #10dan 50ye kadar 50 dahil 20 tane sayı verir
a

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])

In [28]:
#NUMPY BASIC OPERATIONS
a=np.array([1,2,3])
b=np.array([4,5,6])

[5 7 9]


In [ ]:
# iki tane çarpı (**) üzeri yani 3**4 3 üzeri 4 anlamına gelir.

In [31]:
print(a+b)
print(a-b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [32]:
print(np.sin(a)) #a'nın sinüsü

[0.84147098 0.90929743 0.14112001]


In [33]:
print(a<2)#a'nın icinde 2den kücük olanlar true digerleri false

[ True False False]


In [38]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])

In [39]:
#element wise product
print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [40]:
#matrix product
a.dot(b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [41]:
#matrislerle carpma yaparken birincisinin sütunuyla ikincisinin satırı aynı olmak zorunda 
a.dot(b.T) #transposeunu alıp carpabiliriz 

array([[14, 32],
       [32, 77]])

In [43]:
print(np.exp(a))

[[1.43191165 1.0148898  1.8764256  1.78433712 1.0791711 ]
 [1.13896281 2.1236175  2.65413112 1.44666622 1.12795657]
 [1.03151935 1.58845187 1.52830471 1.48521519 1.41374552]
 [1.20594891 1.43711395 2.06662512 2.53875502 1.47169862]
 [1.16347703 2.02111111 2.08605665 1.04403926 2.07478995]]


In [44]:
a=np.random.random((5,5)) #5x5lik 0 ila 1 arasında random sayılar oluşturur.
a

array([[0.88415019, 0.38040099, 0.27149578, 0.58222729, 0.91491441],
       [0.06962633, 0.54947775, 0.51115047, 0.7064878 , 0.84196863],
       [0.38199217, 0.54512019, 0.89155232, 0.38972164, 0.12447186],
       [0.5183799 , 0.1153295 , 0.44431567, 0.76687504, 0.71579553],
       [0.06006412, 0.06504262, 0.61513119, 0.42779639, 0.69197809]])

In [45]:
print(a.sum()) #arraydeki elemanların toplamı
print(a.max()) #arraydeki max eleman
print(a.min()) #arrydeki min eleman

12.465465880804773
0.9149144106214363
0.060064117717787524


In [47]:
print(a.sum(axis=0)) #tüm sütunları tek tek toplar

[1.91421271 1.65537105 2.73364543 2.87310816 3.28912853]


In [48]:
print(a.sum(axis=1)) #satırları tek tek toplar

[3.03318866 2.67871099 2.33285818 2.56069565 1.8600124 ]


In [50]:
print(np.sqrt(a)) #karekök

[[0.94029261 0.61676656 0.52105257 0.7630382  0.95651158]
 [0.26386802 0.74126767 0.71494788 0.84052829 0.91758849]
 [0.61805515 0.73832255 0.94422048 0.6242769  0.3528057 ]
 [0.71998604 0.33960198 0.66657008 0.87571402 0.846047  ]
 [0.24507982 0.25503456 0.78430299 0.65406146 0.8318522 ]]


In [51]:
print(np.square(a)) #a**2 (kare)

[[0.78172156 0.14470491 0.07370996 0.33898862 0.83706838]
 [0.00484783 0.3019258  0.2612748  0.49912502 0.70891118]
 [0.14591802 0.29715602 0.79486554 0.15188296 0.01549324]
 [0.26871772 0.01330089 0.19741642 0.58809732 0.51236325]
 [0.0036077  0.00423054 0.37838638 0.18300975 0.47883367]]


In [52]:
print(np.add(a,a)) #a+a

[[1.76830038 0.76080197 0.54299156 1.16445458 1.82982882]
 [0.13925266 1.09895551 1.02230094 1.4129756  1.68393727]
 [0.76398433 1.09024037 1.78310465 0.77944328 0.24894372]
 [1.03675981 0.23065901 0.88863135 1.53375008 1.43159107]
 [0.12012824 0.13008525 1.23026237 0.85559278 1.38395617]]


In [54]:
x=np.array([[1,2,3],[4,5,6]])
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
#indexing and slicing
array=np.array([1,2,3,4,5,6,7])

In [56]:
print(array[3])

4


In [58]:
print(array[0:4])

[1 2 3 4]


In [59]:
reverse_array=array[::-1] #ters cevirme islemi 
print(reverse_array)

[7 6 5 4 3 2 1]


In [62]:
array1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array1[1,1])

7


In [66]:
print(array1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [67]:
print(array1[:,1]) #satırlardan hepsini sutunlardan 1.ci sutunu al.

[2 7]


In [71]:
print(array1[1,1:4])

[7 8 9]


In [73]:
print(array1[-1,:]) #sutunlardan son sutunu, satırlardan hepsini

[ 6  7  8  9 10]


In [75]:
print(array1[:,-1])

[ 5 10]


In [ ]:
#shape manipulation

In [3]:
myArray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
print(myArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#flatten

In [25]:
a=myArray.ravel()

In [26]:
print(a) #3x3'lük matrisi 1x1 yapmış olduk.

[1 2 3 4 5 6 7 8 9]


In [27]:
array2=a.reshape(3,3) #1x1'lik matrisi 3x3'lük matris yaptık.

In [28]:
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
arrayT=array2.T #transpose almak için kullanıyordu.

In [30]:
print(arrayT) 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [33]:
array5=np.array([[1,2],[3,4],[4,5]])
array5.reshape(2,3)

array([[1, 2, 3],
       [4, 4, 5]])

In [34]:
print(array5) #reshape yaptık fakat aslında array5 degismedi 

[[1 2]
 [3 4]
 [4 5]]


In [36]:
array5.resize((2,3))

In [37]:
print(array5) #resize ile array5'te degisiklik oldu 

[[1 2 3]
 [4 4 5]]


In [38]:
#reshape'de degisiklik yapılmıs olarak kullanmamız ıcın bir degiskene almamız gerekiyor 
#array2=a.reshape(3,3) reshape arrayi direkt olarak degistirmiyor 
#resize ise bizim icin array5=array5.resize((2,3)) gibi islem yaparak kullandıgımız array üzerinde degisiklik yapıyor.

In [39]:
#STAKING ARRAYS (array birlestirme)

In [40]:
array1=np.array([[1,2],[3,4]])
array2=np.array([[-1,-2],[-3,-4]])

In [42]:
print(array1)

[[1 2]
 [3 4]]


In [43]:
 print(array2)

[[-1 -2]
 [-3 -4]]


In [45]:
array3=np.vstack((array1,array2)) #vertical birlestirme

In [46]:
array3

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [47]:
array4=np.hstack((array1,array2)) #horizontal birlestirme

In [48]:
array4

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [49]:
#CONVERT AND COPY ARRAY

In [50]:
liste=[1,2,3,4]                                               #list
array=np.array(liste) #listeden arraye gecmek icin kullanılır. #np.array

In [51]:
liste2=list(array) #arrayden listeye gecmek icin kullanılır

In [52]:
liste2

[1, 2, 3, 4]

In [53]:
type(liste2)

list

In [54]:
a=np.array([1,2,3])
b=a
c=a

In [55]:
b[0]=5

In [56]:
print(a) #b'nin sıfırıncı indexini degistirmeme ragmen a ve c 'de degisti.

[5 2 3]


In [58]:
print(c)

[5 2 3]


In [59]:
#bunun sebebi np.array memory'de depolanirken bir deger olarak degilde memomryde bir alan olarak depolanıyor.
#a , b , c icin memoryde aynı alanı kullandıgımdan iclerinde birini degistirdigimde digerleri de degismis oluyor.

In [60]:
d= np.array([1,2,3])
e=d.copy()
f=d.copy()
f[0]=5

In [61]:
e

array([1, 2, 3])

In [62]:
f #suan sadece f degisti, copy dedimiz icin memoryde uc farkli alan tutuyoruz.

array([5, 2, 3])

In [63]:
d

array([1, 2, 3])